jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        node_12_x:
          node_version: 12.x
      maxParallel: 5

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Install Node.js

      - bash: yarn install
        displayName: Install dependencies

      - bash: yarn lint
        displayName: Lint

      - bash: yarn build
        displayName: Build

      - bash: yarn test:ci
        displayName: Test
