import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
library.add(fas)

export * from './components/Toaster'
export * from './components/Spinner'
export * from './components/Confirm'
export * from './components/Graph'
export * from './components/Button'
export * from './components/Icon'
export * from './components/Badge'
export * from './components/Pill'
export * from './components/Checkbox'
export * from './components/Navbar'
export * from './components/TextField'
export * from './components/Switch'
export * from './components/Radio'
export * from './components/Alert'
export * from './components/TextInput'
export * from './components/Select'
